const ActionType={
    SET_STUDENT:'SET_STUDENT',
    SET_MODEL:'SET_MODEL',
    SET_UPDATE:'SET_UPDATE',
    GET_STUDENT:'GET_STUDENT',
    HANDLE_STUDENT_RESPONSE:'HANDLE_STUDENT_RESPONSE',
    HANDLE_SINGLE_STUDENT_RESPONSE:'HANDLE_SINGLE_STUDENT_RESPONSE',
    HANDLE_DELETE_STUDENT_RESPONSE:'HANDLE_DELETE_STUDENT_RESPONSE',
    HANDLE_UPDATE_STUDENT_RESPONSE:'HANDLE_UPDATE_STUDENT_RESPONSE',
    HANDLE_CREATE_STUDENT_RESPONSE:'HANDLE_CREATE_STUDENT',
    HANDLE_FETCH_REQUEST:'STUDENT_REQUEST_BEGIN',
    HANDLE_RESPONSE_FAILED:'STUDENT_REQUEST_FAILED',
}

export default ActionType;