const ActionConstant = {
    CREATE_CONTACT:"CREATE_CONTACT",
    REMOVE_CONTACT:"REMOVE_CONTACT",
    FETCH_DATA_BEGIN:"FETCH_DATA_BEGIN",
    FETCH_DATA_SUCCESS:"FETCH_DATA_SUCCESS",
    FETCH_DATA_FAILED:"FETCH_DATA_FAILED",
} 
export default ActionConstant;