const ActionType = {
    ADD_STUDENT: 'ADD_STUDENT',
    REMOVE_STUDENT: 'REMOVE_STUDENT',
    UPDATE_STUDENT: 'UPDATE_STUDENT',
    GET_STUDENT: 'GET_STUDENT',
    SET_STUDENT: 'SET_STUDENT',
    SET_MODEL: 'SET_MODEL',
    SET_UPDATE: 'SET_UPDATE',
    CHANGE_NAME: 'CHANGE_NAME',
    CHANGE_ROLLNO: 'CHANGE_ROLLNO',
    SET_STUDENT_OBJ: 'SET_STUDENT_OBJ',
    CHANGE_MARKS: 'CHANGE_MARKS',
}

export default ActionType;